workflows:
  build_apk:
    name: Build RazorBill APK
    max_build_duration: 60
    environment:
      node: "20" # Node version as a string
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Build web assets
        script: |
          npm run build
      - name: Add Capacitor Android
        script: |
          npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
