workflows:
  android-workflow:
    name: Android Build
    environment:
      java: openjdk-17
      node: 20
    scripts:
      - npm ci
      - npm run build
      - npx cap sync android
      - cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
