workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    environment:
      vars:
        NODE_VERSION: 20
      android:
        build_tools: "33.0.2"
        min_sdk: 24
        target_sdk: 34
      jdk: "17"
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Copy web assets to Capacitor
        script: |
          npx cap copy android
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
